apiVersion: apps/v1
kind: Deployment                                            # 1
metadata:
  name: spring-boss-api-s                                 # 2
spec:
  replicas: 3                                                # 3
  containers:
    - image: megaboss77/springboss # 4
      name: spring-boss-api                              # 5
      ports:
        - containerPort: 80                          # 6